# Generated by Django 4.1.7 on 2023-03-14 05:30

from django.db import migrations, models
import scoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_makematch_match_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makematch',
            name='match_pin',
            field=models.CharField(blank=True, default=scoring.models.Makematch.create_new_ref_number, max_length=10, null=True),
        ),
    ]
