# Generated by Django 4.1.7 on 2023-03-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_alter_makematch_match_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maketoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overs', models.IntegerField(default=5)),
                ('batting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bat_team', to='scoring.team')),
                ('toss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Toss_team', to='scoring.team')),
            ],
        ),
    ]
