# Generated by Django 4.1.7 on 2023-03-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_maketoss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makematch',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_222', to='scoring.team'),
        ),
        migrations.AlterField(
            model_name='maketoss',
            name='batting',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maketoss',
            name='toss',
            field=models.CharField(max_length=200),
        ),
    ]
