# Generated by Django 4.1.7 on 2023-03-15 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_alter_maketoss_overs_alter_maketoss_batting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattingScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField()),
                ('balls_faced', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('is_out', models.BooleanField(default=False)),
                ('dismissal_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BowlingScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs_bowled', models.FloatField()),
                ('runs_conceded', models.IntegerField()),
                ('wickets_taken', models.IntegerField()),
                ('maiden_overs', models.IntegerField()),
                ('economy_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('overs', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Maketoss',
        ),
        migrations.AddField(
            model_name='makematch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='scoring.team'),
        ),
        migrations.AlterField(
            model_name='makematch',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='scoring.team'),
        ),
        migrations.AddField(
            model_name='innings',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.makematch'),
        ),
        migrations.AddField(
            model_name='innings',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.team'),
        ),
        migrations.AddField(
            model_name='bowlingscorecard',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.innings'),
        ),
        migrations.AddField(
            model_name='bowlingscorecard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.player'),
        ),
        migrations.AddField(
            model_name='battingscorecard',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.innings'),
        ),
        migrations.AddField(
            model_name='battingscorecard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.player'),
        ),
    ]
