# Generated by Django 4.1.7 on 2023-03-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_battingscorecard_bowlingscorecard_innings_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowlingscorecard',
            name='innings',
        ),
        migrations.RemoveField(
            model_name='bowlingscorecard',
            name='player',
        ),
        migrations.RemoveField(
            model_name='innings',
            name='match',
        ),
        migrations.RemoveField(
            model_name='innings',
            name='team',
        ),
        migrations.DeleteModel(
            name='BattingScorecard',
        ),
        migrations.DeleteModel(
            name='BowlingScorecard',
        ),
        migrations.DeleteModel(
            name='Innings',
        ),
    ]
