# Generated by Django 4.1.7 on 2023-03-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_remove_bowlingscorecard_innings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
