# Generated by Django 4.1.7 on 2023-03-25 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0014_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs', models.DecimalField(decimal_places=1, max_digits=3)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.makematch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.player')),
            ],
        ),
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('out', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.makematch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.player')),
            ],
        ),
    ]
