# Generated by Django 4.1.7 on 2023-03-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0015_bowling_batting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batting',
            old_name='balls',
            new_name='balls_faced',
        ),
    ]
