# Generated by Django 4.1.7 on 2023-03-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0016_rename_balls_batting_balls_faced'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batting',
            new_name='Batter',
        ),
        migrations.RenameModel(
            old_name='Bowling',
            new_name='Bowler',
        ),
    ]
