# Generated by Django 4.1.7 on 2023-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0017_rename_batting_batter_rename_bowling_bowler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'team')},
        ),
    ]
