# Generated by Django 4.1.7 on 2023-03-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0018_alter_team_name_alter_player_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captian_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captian_phone',
        ),
    ]
