# Generated by Django 4.1.7 on 2023-03-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0020_player_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batter',
            name='balls_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batter',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batter',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batter',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
    ]
