# Generated by Django 4.1.7 on 2023-04-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0023_remove_makematch_match_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makematch',
            old_name='team_a_name',
            new_name='team_1',
        ),
        migrations.RenameField(
            model_name='makematch',
            old_name='team_b_name',
            new_name='team_2',
        ),
    ]
