# Generated by Django 4.1.7 on 2023-04-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0024_rename_team_a_name_makematch_team_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makematch',
            name='tournament_name',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='scoring.tournament'),
        ),
    ]
