# Generated by Django 4.1.7 on 2023-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0026_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='makematch',
            name='overs',
            field=models.IntegerField(default=5),
        ),
    ]
