# Generated by Django 4.1.7 on 2023-05-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0027_makematch_overs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makematch',
            name='overs',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
