# Generated by Django 4.1.7 on 2023-05-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0028_alter_makematch_overs'),
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
